name: Fetch News
on:
  workflow_dispatch:
  schedule:
    - cron: '0 */4 * * *'
jobs:
  fetch-data:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        language: [ en ]
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2

      - name: Fetch API Data - ${{ matrix.language }}📦
        uses: JamesIves/fetch-api-data-action@releases/v1
        with:
          ENDPOINT: https://newsapi.org/v2/everything?q=entertainment%20news&language=${{ matrix.language }}&sortBy=popularity&apiKey=${{ secrets.NEWS_API_KEY }}
          retry: true

      - name: Stage - ${{ matrix.language }}🚀
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GIT_CONFIG_NAME: GitHub Actions Bot
          GIT_CONFIG_EMAIL: <>
          BRANCH: stage
          FOLDER: fetch-api-data-action
          TARGET_FOLDER: ${{ matrix.language }}
          SINGLE_COMMIT: true

  merge:
    if: ${{ always() }}
    needs: fetch-data
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2

      - name: Merge 🚀
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git fetch origin
          git checkout gh-pages
          git merge --allow-unrelated-histories -X theirs origin/stage
          git push --force origin gh-pages
